language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
- '0.11'
- '0.10'
- iojs
after_success: bash ./deploy-gh-pages.sh
env:
  global:
  - GH_REF: github.com/jimpurbrick/crestmatic.git
  - secure: n6P+Yv93Aho7ikVZ0b0MG0kLPyIUJDdfXx6oohXD0nbVfcoPxaIwKzCN/jt4s2HYv++RwKYTxL+eqOT5w80xdmfyDsgh7CshO+FRZEnxGI08gVCxpqd/wJcHh5uGbG8q+tDax2ZlcD/wmC0TVcx2LiTYgwJpMDA6uACnuv5YAriSMSoCVTIIjL51O7/hmWispenQBtYrJknc0xjZvpD/hLXLSUMLtq5pnS+/4+wtsJloSIJ3ex3XLb932m9h143/nW+xlv7nrXTP/aHI/otpuFpW4XvmqKPvmlQhpI8UiKEgDfuglLzUSItqOuWNpTbzmSpKA/2fS6LT+MVXCwZjFm5AKz/NetZlwDZau0OejNsYou7Bh3L6EU2LnK2OjJYLkGpXlypcTLMaU8iUBx0S0Y9Hs7w7VWomMP/Ulvw0MITbZw7DGj64R96BkEsxt0jwi9q8J4fKHKBDLvSbD4xT5YeNUSgveP0w9mCtVN/+A8kNhOAJ9o+oe3SP9q3pFFDX4eeIQUyr/BkFhgI/mgr6goLluPjicC5ShMI/YYjutHIpAtzP16pRPF9mSapDQMnIrkh+XssrQELuM5foGgFjArsoQzcwnr8eVChLSYnbMvFi8msaTcIqpSsYzz7QBrQuO1t/Hg6o6XdzP7sMszS+qnCeI3m5X0EbkhWA8fKQW6U=
